# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies
RUN npm ci

# Copy source code
COPY . .

# Build the TypeScript code
RUN npm run build

# Set environment variable for Discord token
ENV DISCORD_TOKEN=""

# Expose HTTP port
EXPOSE 8080

# Default command to run the MCP server with HTTP transport and Discord token
CMD ["node", "build/index.js", "--transport", "http", "--port", "8080"]