# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json package-lock.json ./

# Install dependencies without running scripts
RUN npm install --ignore-scripts

# Copy source code
COPY . .

# Build the TypeScript code
RUN npm run build

# Expose HTTP port (default 3000 as specified in smithery.yaml)
EXPOSE 3000

# Default command to run the MCP server with HTTP transport
CMD ["node", "build/index.js", "--transport", "http", "--port", "3000"]
